# Python Insights - Analisando Dados com Python

### Case - Cancelamento de Clientes

Você foi contratado por uma empresa com mais de 800 mil clientes para um projeto de Dados. Recentemente a empresa percebeu que da sua base total de clientes, a maioria são clientes inativos, ou seja, que já cancelaram o serviço.

Precisando melhorar seus resultados ela quer conseguir entender os principais motivos desses cancelamentos e quais as ações mais eficientes para reduzir esse número.

A base de dados se encontra nesse repositório com o nome 'cancelamentos.csv'
É preciso instalar o Jupyter no VSCode pra executar.

In [258]:
#What we do?
#import DB
#Visualize DB
#Fix DB issues
#Analysis of cancellations
#Analysis of the causes of cancellations (How do the columns cause impact cancellation?)

#import DB
import pandas as pd

cancellations_table = pd.read_csv("cancellations.csv")
display(cancellations_table)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,349936.0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,100634.0,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,301263.0,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,119358.0,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,130955.0,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,195680.0,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,43477.0,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,169273.0,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,310693.0,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,251915.0,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

In [259]:
#Well... We don't need the 'CustomerID' column, so let's drop it
# cancellations_table.drop(columns=['CustomerID'], inplace=True) # It works too, but let's do it in a different way
cancellations_table = cancellations_table.drop("CustomerID", axis=1)
display(cancellations_table)
display(cancellations_table.info())

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
49995,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   50000 non-null  float64
 1   sexo                    49997 non-null  object
 2   tempo_como_cliente      49998 non-null  float64
 3   frequencia_uso          50000 non-null  float64
 4   ligacoes_callcenter     50000 non-null  float64
 5   dias_atraso             50000 non-null  float64
 6   assinatura              50000 non-null  object
 7   duracao_contrato        50000 non-null  object
 8   total_gasto             50000 non-null  float64
 9   meses_ultima_interacao  50000 non-null  float64
 10  cancelou                50000 non-null  float64
dtypes: float64(8), object(3)
memory usage: 4.2+ MB

None

In [260]:
#As we can see above, in the non-null column we have different values, meaning there are comlumns with empty values. 
#Let's drop the rows with empty values, as we don't want to analyze incomplete data.

#Looking more closely, we can see that the 'sexo' column has 3 empty values. Let's check what are these rows.
display(cancellations_table[cancellations_table["sexo"].isna()])

#And the 'tempo_como_cliente' column
display(cancellations_table[cancellations_table["tempo_como_cliente"].isna()])

#It's just to know more. So we have 4 rows (5, 12, 17 and 18) with empty values. Let's drop them.
cancellations_table = cancellations_table.dropna()

#Let's check the info of the table after dropping the rows with empty values.
display(cancellations_table.info())

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
5,30.0,NaN,NaN,12.0,3.0,7.0,Standard,Quarterly,641.78,7.0,0.0
12,36.0,NaN,9.0,13.0,1.0,8.0,Standard,Quarterly,719.77,22.0,0.0
17,25.0,NaN,47.0,18.0,2.0,3.0,Basic,Quarterly,707.31,7.0,0.0

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
5,30.0,NaN,NaN,12.0,3.0,7.0,Standard,Quarterly,641.78,7.0,0.0
18,29.0,Female,NaN,4.0,2.0,8.0,Standard,Annual,904.00,25.0,1.0

<class 'pandas.core.frame.DataFrame'>
Index: 49996 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   49996 non-null  float64
 1   sexo                    49996 non-null  object
 2   tempo_como_cliente      49996 non-null  float64
 3   frequencia_uso          49996 non-null  float64
 4   ligacoes_callcenter     49996 non-null  float64
 5   dias_atraso             49996 non-null  float64
 6   assinatura              49996 non-null  object
 7   duracao_contrato        49996 non-null  object
 8   total_gasto             49996 non-null  float64
 9   meses_ultima_interacao  49996 non-null  float64
 10  cancelou                49996 non-null  float64
dtypes: float64(8), object(3)
memory usage: 4.6+ MB

None

In [261]:
#The data base has already been cleaned, so we can start the analysis of the cancellations. 
# Let's check the number of cancellations and the number of non-cancellations.
display(cancellations_table["cancelou"].value_counts())

#And in terms of percentage?
print("Amount of cancellations and non-cancellations in percentage:")
display(cancellations_table["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

cancelou
1.0    28393
0.0    21603
Name: count, dtype: int64

Amount of cancellations and non-cancellations in percentage:

cancelou
1.0    56.8%
0.0    43.2%
Name: proportion, dtype: object

In [295]:
#What types of contract duration do we have?
display(cancellations_table["duracao_contrato"].unique())

#So we have 3 types of contract duration. Let's check the amount and percentage of cancellations for each type of contract.
display(cancellations_table.groupby("duracao_contrato")["cancelou"].value_counts().unstack())
display(cancellations_table.groupby("duracao_contrato")["cancelou"].value_counts(normalize=True).unstack().map("{:.1%}".format))

#Another way to view the data average, generally sorted by 'duracao_contrato' column.
display(cancellations_table.groupby("duracao_contrato").mean(numeric_only=True))

array(['Annual', 'Monthly', 'Quarterly'], dtype=object)

cancelou              0.0     1.0
duracao_contrato
Annual            10802.0  9354.0
Monthly               NaN  9884.0
Quarterly         10801.0  9155.0

cancelou            0.0     1.0
duracao_contrato
Annual            53.6%   46.4%
Monthly            nan%  100.0%
Quarterly         54.1%   45.9%

,idade,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,total_gasto,meses_ultima_interacao,cancelou
duracao_contrato,,,,,,,,
Annual,38.783985,31.416452,15.910449,3.277585,12.533985,650.925840,14.231544,0.464080
Monthly,41.428470,30.677964,15.577600,4.923917,15.078814,547.508921,15.392655,1.000000
Quarterly,38.833935,31.522099,15.842504,3.256113,12.480006,654.102443,14.364602,0.458759

In [ ]:
#Let's see the graph representation of the number of CANCELLATIONS for each CONTRACT DURATION.
import plotly.express as px

graph_cancellations_by_contract = px.bar(cancellations_table.groupby("duracao_contrato")["cancelou"].value_counts().unstack(),
                                         text_auto=True, title="Number of Cancellations by Contract Duration" , labels={"value": "Number of contracts", "duracao_contrato": "Contract Duration", "cancelou": "Cancellation Status"})
display(cancellations_table)
graph_cancellations_by_contract.show()

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
49995,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

In [284]:
#Based on what we've seen so far, we can see that the 'duracao_contrato' column has a strong impact on the cancellation. 
#Montly contracts have a cancellation rate of 100%, while the other average 45%. 
#Therefore, we need to exclude the monthly contract from our analysis to clearly visualize the impact of the total cancellations volume. 
#Let's do that!

filtered_table_different_by_monthly = cancellations_table[cancellations_table["duracao_contrato"] != "Monthly"]
display(filtered_table_different_by_monthly["cancelou"].value_counts())

display(filtered_table_different_by_monthly.groupby("duracao_contrato")["cancelou"].value_counts(normalize=True).unstack().map("{:.1%}".format))

print("Amount of cancellations and non-cancellations in percentage:")
display(filtered_table_different_by_monthly["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

cancelou
0.0    21603
1.0    18509
Name: count, dtype: int64

cancelou            0.0    1.0
duracao_contrato
Annual            53.6%  46.4%
Quarterly         54.1%  45.9%

Amount of cancellations and non-cancellations in percentage:

cancelou
0.0    53.9%
1.0    46.1%
Name: proportion, dtype: object

In [ ]:
#Let's show the comparison of the cancellation rates BEFORE and AFTER filtering out the monthly contracts.

#Taking the cancellation rates before filtering out the monthly contracts.
resume_cancellations_before_monthly_filter = (
    cancellations_table["cancelou"]
    .value_counts(normalize=True)
    .rename("Before removing Monthly contracts")
)

#Taking the cancellation rates after filtering out the monthly contracts.
resume_cancellations_after_monthly_filter = (
    filtered_table_different_by_monthly["cancelou"]
    .value_counts(normalize=True)
    .rename("After removing Monthly contracts")
)

#Let's create a new table to compare the cancellation rates before and after filtering out the monthly contracts.
relation_cancellations = pd.concat(
    [resume_cancellations_before_monthly_filter, resume_cancellations_after_monthly_filter],
    axis=1
    ).reset_index()

#Let's rename the columns to make it more clear.
relation_cancellations = relation_cancellations.melt(
    id_vars="cancelou",
    var_name="Table",
    value_name="Percent"
)

#Let's create a new column to make it more clear.
relation_cancellations["status"] = relation_cancellations["cancelou"].map({
    0.0: "Active Clients",
    1.0: "Cancelled Clients"
})
display(relation_cancellations)

fig = px.bar(
    relation_cancellations,
    x="Table",
    y="Percent",
    color="status",
    barmode="stack",
    text_auto=".1%",
    title="Cancellation Rate — Before vs. After",
    color_discrete_map={
        "Cancelled Clients": "#E74C3C",
        "Active Clients": "#3498DB"
    },
    labels={
        "Percent": ""
    }
)

fig.show()

#For Managers: Ok, now that we've seen a 10.7% reduction in cancellations (56.8% -> 46.1%),
# we should consider offering a larger discount on the other plans to discourage users from choosing the monthly plan.

   cancelou                              Table   Percent             status
0       1.0  Before removing Monthly contracts  0.567905  Cancelled Clients
1       0.0  Before removing Monthly contracts  0.432095     Active Clients
2       1.0   After removing Monthly contracts  0.461433  Cancelled Clients
3       0.0   After removing Monthly contracts  0.538567     Active Clients

In [ ]:
#Let's get the result of table counting by subscription type
display(filtered_table_different_by_monthly["assinatura"].value_counts(normalize=True))
display(filtered_table_different_by_monthly.groupby("assinatura").mean(numeric_only=True))
#As we can see, the 'assinatura' hasen't a strong impact on the cancellation rate. 
#Let's do another graph to see if we can find a column that has a strong impact on the cancellation rate.

for column in filtered_table_different_by_monthly.columns:
    graph = px.histogram(filtered_table_different_by_monthly, x=column, color="cancelou", width=500)
    # graph.show()

assinatura
Standard    0.343264
Premium     0.333466
Basic       0.323270
Name: proportion, dtype: float64

,idade,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,total_gasto,meses_ultima_interacao,cancelou
assinatura,,,,,,,,
Basic,38.777049,32.266908,15.938459,3.328064,12.538752,648.339261,14.317036,0.476517
Premium,38.885766,31.120813,15.762111,3.238038,12.430697,653.459842,14.306071,0.453947
Standard,38.764035,31.055850,15.929697,3.237345,12.551601,655.504070,14.271479,0.454499

In [387]:
#So... We observe that cancellation rates are higher among people over the age of 50;
#Women have a higher cancellation rate than men;
#More than four calls to the call center results in cancellation;
#A payment delay of more than 20 days usually results in cancellation.

#Let's start with CALL CENTER calls, removing registers when call_center calls bigger than 5
filtered_table_different_by_monthly_and_calls = filtered_table_different_by_monthly[
    filtered_table_different_by_monthly["ligacoes_callcenter"]<5
    ]

#We can see the summary of cancellation for each call number
display(filtered_table_different_by_monthly_and_calls
        .groupby("ligacoes_callcenter")["cancelou"]
        .value_counts(normalize=True)
        .unstack()
        .map("{:.1%}".format))

#Showing two plain text rates, before and after call center filtering
display(filtered_table_different_by_monthly["cancelou"]
        .value_counts(normalize=True)
        .map("{:.1%}".format))
display(filtered_table_different_by_monthly_and_calls["cancelou"]
        .value_counts(normalize=True)
        .map("{:.1%}".format))

# #Let's create a new column to make it more clear.
# filtered_table_different_by_monthly_and_calls["status"] = filtered_table_different_by_monthly_and_calls["cancelou"].map({
#     0.0: "Active Clients",
#     1.0: "Cancelled Clients"
# })

graph_without_filtering_calls = px.histogram(filtered_table_different_by_monthly, x=column, color="cancelou", width=500,
                      title="Cancelled rate before improving the call center")
graph_without_filtering_calls.show()

graph_with_filtering_calls = px.histogram(filtered_table_different_by_monthly_and_calls, x=column, color="cancelou", width=500,
                     title="Cancelled rate after improving the call center")
graph_with_filtering_calls.show()

#For Managers: Ok, now that we've seen further 19.7% reduction in cancellations (46.1% -> 21.4),
#we should consider to improve the call center to offer definitive solutions.

cancelou               0.0    1.0
ligacoes_callcenter
0.0                  78.8%  21.2%
1.0                  78.7%  21.3%
2.0                  77.8%  22.2%
3.0                  69.2%  30.8%
4.0                  51.5%  48.5%

cancelou
0.0    53.9%
1.0    46.1%
Name: proportion, dtype: object

cancelou
0.0    73.6%
1.0    26.4%
Name: proportion, dtype: object

In [ ]:
#A PAYMENT DELAY of more than 20 days usually results in cancellation.

filtered_table_different_by_monthly_and_calls_and_less_payment_delay = filtered_table_different_by_monthly_and_calls[
    filtered_table_different_by_monthly_and_calls["dias_atraso"] < 20
    ]

#Showing two plain text rates, before and after payment delay filtering
display(filtered_table_different_by_monthly_and_calls["cancelou"]
        .value_counts(normalize=True)
        .map("{:.1%}".format))
display(filtered_table_different_by_monthly_and_calls_and_less_payment_delay["cancelou"]
        .value_counts(normalize=True)
        .map("{:.1%}".format))
#Now we have 18.3% of cancellation rate.

graph_with_delay_filtering = px.histogram(filtered_table_different_by_monthly_and_calls_and_less_payment_delay, 
                                          x=column, 
                                          color="cancelou",
                                          width=500)
graph.show()

#For Managers: Maybe could we offer a discount for ponctual payments or even for early.

cancelou
0.0    73.6%
1.0    26.4%
Name: proportion, dtype: object

cancelou
0.0    81.7%
1.0    18.3%
Name: proportion, dtype: object

In [421]:
#Let's see the final chart/ graph.

resume_cancellations = (
    cancellations_table["cancelou"]
    .value_counts(normalize=True)
    .rename("Original table")
)

#Taking the final cancellation rates.
resume_cancellations_with_monthly_filter = (
    filtered_table_different_by_monthly["cancelou"]
    .value_counts(normalize=True)
    .rename("After removing Monthly contracts")
)

resume_cancellations_with_monthly_filter_and_calls_filter = (
    filtered_table_different_by_monthly_and_calls["cancelou"]
    .value_counts(normalize=True)
    .rename("After removing more than 4 call center calls")
)

resume_cancellations_with_monthly_filter_and_calls_filter_and_payment_dalay_filter = (
    filtered_table_different_by_monthly_and_calls_and_less_payment_delay["cancelou"]
    .value_counts(normalize=True)
    .rename("After removing delay payments")
)

relation_cancellations_concat = pd.concat(
    [
        resume_cancellations,
        resume_cancellations_with_monthly_filter,
        resume_cancellations_with_monthly_filter_and_calls_filter,
        resume_cancellations_with_monthly_filter_and_calls_filter_and_payment_dalay_filter
    ],
    axis=1
).reset_index()

relation_cancellations_concat = relation_cancellations_concat.melt(
    id_vars="cancelou",
    var_name="Table",
    value_name="Cancelled"
)

relation_cancellations_concat["Status"] = relation_cancellations_concat["cancelou"].map({
    0.0: "Active Clients",
    1.0: "Cancelled Clients"
})
display(relation_cancellations_concat)

final_graph = px.bar(
    relation_cancellations_concat,
    x="Table",
    y="Cancelled",
    color="Status",
    barmode="stack",
    text_auto=".1%",
    title="Final graph",
    color_discrete_map={
        "Active Clients": "#3498DB",
        "Cancelled Clients": "#E74C3C"
    },
    labels={
       "Cancelled": "Cancelled (0/1)",
       "Table": "In accordance with the removal of bad things"
    }
)

final_graph.show()

,cancelou,Table,Cancelled,Status
0,1.0,Original table,0.567905,Cancelled Clients
1,0.0,Original table,0.432095,Active Clients
2,1.0,After removing Monthly contracts,0.461433,Cancelled Clients
3,0.0,After removing Monthly contracts,0.538567,Active Clients
4,1.0,After removing more than 4 call center calls,0.263606,Cancelled Clients
5,0.0,After removing more than 4 call center calls,0.736394,Active Clients
6,1.0,After removing delay payments,0.183264,Cancelled Clients
7,0.0,After removing delay payments,0.816736,Active Clients